const archetype = {
	byname: {
		warrior: {
			playerSizes: { w: 1, h: 1, d: 1 },
			isMoving: false,
			isFalling: false,
			isJumping: false,
			isRotating: false,
			jumpForce: 0.25,
			velocity: { x: 0, y: 0, z: 0 },
			moveSpeed: { x: 0.1, y: 0.1, z: 0.1 },
			defaultPos: { x: 0, y: 0, z: 0 },
			color: 0x2500ff,
			archetype: "warrior",
			name: "Alice",
		},
		healer: {
			playerSizes: { w: 0.6, h: 0.6, d: 0.2 },
			isMoving: false,
			isFalling: false,
			isJumping: false,
			isRotating: false,
			jumpForce: 0.25,
			velocity: { x: 0, y: 0, z: 0 },
			moveSpeed: { x: 0.1, y: 0.1, z: 0.1 },
			defaultPos: { x: 0, y: 0, z: 3 },
			color: 0x0000ff,
			archetype: "healer",
			name: "Bob",
		},
	},
	init: function () {},
};
